name: CI/CD Pipeline

on:
  push:
    branches: ["*"]

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: org_chat_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: "1.14"
          otp-version: "25"

      - name: Install dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Run Credo
        run: mix credo --strict

      - name: Compile
        run: mix compile

      - name: Create and migrate DB
        run: |
          mix ecto.create
          mix ecto.migrate

      - name: Run tests
        run: mix test

